# Generated by Django 3.0.8 on 2020-07-16 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200716_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mulher'), ('H', 'Homem'), ('MT', 'Mulher Trans'), ('HT', 'Homem Trans')], max_length=2, null=True),
        ),
    ]
