# Generated by Django 3.0.8 on 2020-07-16 20:14

import apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200716_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modificado em')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Endereço do ocorrido')),
                ('when_happen', models.DateField(blank=True, null=True, verbose_name='Dia do ocorrido')),
                ('time_when_happen', models.TimeField(blank=True, null=True, verbose_name='Horário do ocorrido')),
                ('bus_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do ônibus')),
                ('bus_license_plate', models.CharField(blank=True, max_length=30, null=True, verbose_name='Placa do ônibus')),
                ('video_or_image', models.FileField(blank=True, null=True, upload_to=apps.user.models.user_file_directory_path, verbose_name='Vídeo ou imagem do ocorrido')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
